name: Remove Jupyter Notebook Outputs

on:
  push:
    paths:
      - '**/*.ipynb'

jobs:
  remove_outputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install nbconvert
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Remove outputs from notebooks
      run: |
        changed_files=$(git diff --name-only origin/main | grep '\.ipynb$')
        if [ -n "$changed_files" ]; then
          for notebook in $changed_files; do
            resources_changed=$(git diff --unified=0 $notebook | grep '^[-+][^-+]# Resources$')
            if [ -n "$resources_changed" ]; then
              tmpfile=$(mktemp)
              python $GITHUB_WORKSPACE/remove_outputs.py $notebook $tmpfile
              mv $tmpfile $notebook
              git add $notebook
            else
              echo "No resource changes found in $notebook."
            fi
          done
        else
          echo "No notebook files with changes found."
        fi
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Commit changes
      run: |
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit."
        else
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Remove notebook outputs [skip ci]"
          git push
        fi
