name: Remove Jupyter Notebook Outputs

on:
  push:
    paths:
      - '**/*.ipynb'

jobs:
  remove_outputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install nbconvert
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Remove outputs from notebooks
      run: |
        for notebook in $(git diff --name-only origin/main | grep '\.ipynb$'); do
          tmpfile=$(mktemp)
          python $GITHUB_WORKSPACE/remove_outputs.py $notebook $tmpfile
          mv $tmpfile $notebook
          git add $notebook
        done
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git commit -m "Remove notebook outputs [skip ci]"
        git push
